# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d1c3eb16d83a67f9d55ba2a4631f5bf017efc28f0a9f17783f90da3e1e2f351cc9ce8a6170d59cfddfff12e080c34b8e826fcd0add88eb7a3262a400228e089

test:
  secret_key_base: 6c4b6ed83d9ca6aee3efe608d79cc1cc7d5206bb9b3e1e3b0afd9053797751dfd4992d72f62735643ab317fa91db05515d820d9b22ebe7fdda3210b0f141987e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
